# loss函数

`loss`函数都继承自`_Loss`,`_Loss`继承自`nn.Module`

`_Loss`接受三个参数
```text
size_average        // 这个参数废弃了
reduce              // 这个参数也是之前的废弃了
reduction = "mean"    // mean:对batch内的值取平均，sum:对batch内的值求和,none:不处理，返回高维张量
```


In [ ]:
# L1Loss取差值的绝对值

import torch
import torch.nn as nn

input = torch.tensor([[2, 3], [4, 5]]).float()
target = torch.tensor([[3, 4], [5, 6]]).float()

loss1 = nn.L1Loss(reduction="mean")
loss2 = nn.L1Loss(reduction="sum")
loss3 = nn.L1Loss(reduction="none")

output1 = loss1(input, target )
output2 = loss2(input, target )
output3 = loss3(input, target )

print(output1)
print(output2)
print(output3)


tensor(1.)
tensor(4.)
tensor([[1., 1.],
        [1., 1.]])


In [29]:
# MSE 均方误差, 结果是差值的绝对值

loss4 = nn.MSELoss(reduction="none")        # none保留高维张量的形状

input = torch.tensor([[2, 3], [4, 5]]).float()
target = torch.tensor([[4, 5], [6, 7]]).float()

output4 = loss4(input, target)

print(output4)



tensor([[4., 4.],
        [4., 4.]])


In [93]:
# CrossEntropyLoss 交叉熵，把高维张量映射成一个

input = torch.tensor([[1, 2], [3, 4]]).float()
target = torch.tensor([1, 1]).long()

loss5 = nn.CrossEntropyLoss(reduction="none")

output = loss5(input, target)

print(output)



tensor([0.3133, 0.3133])
